### ISSUE TITLE
Issue Exporting STLs and Render/Show

### ISSUE THREAD

**Issue by anniedoris** [BJCaasenbrood/SorotokiCode#15] opened 2024-04-02 17:54 UTC
Hi Brandon,

Thanks for this cool repo! I am working on implementing my own SDF and I'd like to export it as an STL. I saw that this is a feature on [this](https://bjcaasenbrood.github.io/SorotokiCode/sdf/operations/) page (second example). When I try to export an stl using the most recent version of Sorotoki, I am not able to export an .stl. I get an error: `Unrecognized method, property, or field 'export' for class 'Sdf'.` I tried searching the whole code base for `export` and didn't find anything. Is it possible that this functionality got accidentally removed? And if so, might it be possible to add it back?

I've also noticed something strange with `sdf.render` versus `sdf.show.` I have implemented a basic cube function: `S2 = sCube([0.1, 0.1, 0.1], [9.8, 1.8, 1.8]);` When I visualize the cube using `.show()` I get the following image, which is what I would expect:

<img width="509" alt="Screenshot 2024-04-02 at 1 50 53 PM" src="https://github.com/BJCaasenbrood/SorotokiCode/assets/43191615/be9fefbd-0f68-4d72-a85c-99e54479e776">

However, when I visualize the cube using `.render('Quality',50)` I get the following unexpected image:
<img width="493" alt="Screenshot 2024-04-02 at 1 51 09 PM" src="https://github.com/BJCaasenbrood/SorotokiCode/assets/43191615/3186072f-01c0-4edb-b6dd-2bdaf9624908">

Do you have any suggestions for what might be causing the render and show functions to visualize this cube differently?

Thanks for your help!

**Comment by BJCaasenbrood** [comment] 2024-04-03 13:46
Hey Annie, you are right. I see that I haven't pushed the latest version of SorotokiSdf. The `sdf.export` function should now be available. The rendering issue for `.render()` (and subsequently `.export()`) is caused by a too narrow bounding box when using the Marching Cube Algorithm. When the bounding box is too small, the algorithm will likely not place/render all faces. 

To increase the bounding box of the SDF function, you can overwrite it as follows: `sdf.BdBox = [....]`. Initially, I had the offset set at $\delta = 1\cdot10^{-6}$ in respect to the size of the bounding box. I've modified this for `sdf.export` and `sdf.render` to now consider a 2% larger bounding box automatically -- seems to have fixed the issue.

Running the code below should produce an STL file named test.stl:

```matlab
sdf = sCube([0.1, 0.1, 0.1], [9.8, 1.8, 1.8]);
sdf.export();
```

Issue fixed with https://github.com/BJCaasenbrood/SorotokiSdf/commit/431df70a7428249a251ad0c8009e544f74f63988

![image](https://github.com/BJCaasenbrood/SorotokiCode/assets/36262141/29d611b3-ec3d-41e9-a6e3-d8e360bf02ec)

**Comment by BJCaasenbrood** [comment] 2024-04-03 13:47
Issue fixed with https://github.com/BJCaasenbrood/SorotokiSdf/commit/431df70a7428249a251ad0c8009e544f74f63988

**Closed by BJCaasenbrood** 2024-04-03 13:47 UTC
