### ISSUE TITLE
A problem of duplicate file names under windows

### ISSUE THREAD

**Issue by muyi-max** [BJCaasenbrood/SorotokiCode#6] opened 2022-04-17 12:57 UTC
Your work is great, I am a beginner and learning from you. When I unzip the file under windows, the decompression software suggests that there are 4 duplicate files, "hex2rgb.m, rgb2hex.m, admap.m, isomse3.r" I chose to overwrite the operation, I wonder if this will have a bad effect on the use of the program? The content of the screenshot is the path of the file
![Snipaste_2022-04-17_20-55-47](https://user-images.githubusercontent.com/71560804/163715291-c16feaf3-8fc0-43a7-915d-853412c34efe.png)

**Comment by BJCaasenbrood** [comment] 2022-04-17 16:22
Hi, thanks for showing interest for the toolkit. This is indeed an issue with the Window's version of Matlab. In Windows, Matlab doesn't see the difference between functions isomSE3.m and isomse3.m. I believe Linux and Mac, do.

Is slightly annoying, since these function are related to the group SE(3) and it's algebra se(3). 

I'll fix this as soon as possible. Thanks for letting me know!

**Comment by BJCaasenbrood** [comment] 2022-04-17 16:25
Problem: Fixi problem in Windows with capital letter functions, leading to duplicate files. Files affect are:

Hex2rgb, isomse3, rgb2hex, admap

**Comment by BJCaasenbrood** [comment] 2022-04-18 10:53
The issue is now fixed.
Hex2rgb -> hex2rgb.m
RGB2hex -> rgb2hex.m
isomSE3 is now separated into two files: hat and wedge that perform the isomorphic mappings between se3 -> R6 and so3 -> R3

**Closed** 2022-04-18 10:54 UTC
